version: '3.8'

services:
  admin:
    build:
      context: ./appstore-admin
      dockerfile: Dockerfile
    image: sendyclone-admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - localstack

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: sendy_db
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4572:4572" # S3
    environment:
      SERVICES: s3
      DEBUG: 1
      PERSISTENCE: 1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"