spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sendy_db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&connectTimeout=10000&socketTimeout=30000&prepStmtCacheSize=100&prepStmtCacheSqlLimit=2048&cachePrepStmts=true&rewriteBatchedStatements=true&useServerPrepStmts=true&testWhileIdle=true&validationQuery=SELECT 1&timeBetweenEvictionRunsMillis=900000
    username: root
    password: 1111
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 100
      maximum-pool-size: 100
      max-lifetime: 240000
      idle-timeout: 200000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://mysql:3306/sendy_db
    user: root
    password: 1111
