spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sendy_db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&connectTimeout=10000&socketTimeout=30000&prepStmtCacheSize=100&prepStmtCacheSqlLimit=2048&cachePrepStmts=true&rewriteBatchedStatements=true&useServerPrepStmts=true
    username: root
    password: 1111
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 100
      maximum-pool-size: 100
      max-lifetime: 240000
      idle-timeout: 200000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true
  flyway:
    enabled: false
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    com.zaxxer.hikari: DEBUG

aws:
  s3:
    accessKey: test
    secretKey: test